### PR TITLE
Fixed "format" not being saved internally

### LINKED ISSUE #17: format parameter can't be changed via the GUI
I'm currently investigating this and will probably provide a PR - just wanted to let you know, I found this problem:

The values `format` of capture/playback device and convolution filters are not properly updated in the internal state.
If you change one of these and "Save to file", the file doesn't contain the new values.

### PR DESCRIPTION
**Pull request by JWahle**
Fixed "format" not being saved internally for capture/playback devices and convolution filters.
This fixes #17.

The solution is pretty hacky, but I do not see a clean way to fix this.
When I fixed it for the `format` field, it broke all other `EnumSelect`s.
At least this points to the cause of the error, so it saves you some debugging time, if you want to fix it cleanly.

### CODE REVIEW

File: src/common.js [hunk 1]
```diff
@@ -138,7 +138,13 @@ export class EnumSelect extends React.Component {
 
   handleChange(event) {
     this.setState({ value: event.target.value });
-    this.props.onSelect(event.target.value);
+    if (this.props.desc === "format")
```
Comment (HEnquist) [inline src/common.js:141]: This is a bit hacky, but it's better than being completely broken! 
Could you just add a comment here, something like "TODO: fix this in a nicer way".

**Comment by JWahle** [comment]
Done.
